### ISSUE TITLE
failed to remove extension "..." as it is not installed

### ISSUE THREAD

**Issue by bostick** [docker/extensions-sdk#215] opened 2022-09-05 23:37 UTC
I am developing a Docker Desktop for ZeroTier and have run into a bit of trouble. Namely, I cannot uninstall the extension as it is being developed!

This is with version 4.12.0 that was just released.

Here is what I'm trying:
```
brenton@Brentons-M1-MacBook-Pro zerotier-docker-extension % docker extension ls
ID                          PROVIDER            VERSION             UI                  VM                  HOST
zerotier-docker-extension   ZeroTier Inc.                           1 tab(ZeroTier)     Not started         -
brenton@Brentons-M1-MacBook-Pro zerotier-docker-extension % docker extension rm zerotier-docker-extension
failed to remove extension "zerotier-docker-extension" as it is not installed
```

I have been able to uninstall other extensions using the same method, so I have seen that work.

Even if unsupported, please let me know where I can uninstall the extension from my machine and start over. Reinstalling Docker Desktop would be fine. I am just interested in removing this development extension through whatever means.

**Comment by bostick** [comment] 2022-09-05 23:38
Here is a screenshot after clicking the Uninstall button:

<img width="1382" alt="Screen Shot 2022-09-05 at 7 31 07 PM" src="https://user-images.githubusercontent.com/183619/188520870-aeb7feee-0f9e-4ba2-98fa-be5c27755866.png">

**Comment by benja-M-1** [comment] 2022-09-06 06:56
Hi @bostick thanks for reporting this. It is a known issue, we have some cleanup to do... Somehow it helps to prioritize it!...

The problem is that the name of the extension is not valid. It should be something like 'zerotier/docker-extension', with a namespace (zerotier) and an image name (docker-extension).

To remove the extension you will have to do it manually:
- remove the extension folder located in '/Users/yourusername//Library/Containers/com.docker.docker/Data/extensions'
- restart Docker Desktop

**Comment by bostick** [comment] 2022-09-06 14:27
Thank you! I figured it had to do with the name, but I could not figure out where to manually remove the files.

**Comment by averche** [comment] 2022-10-25 22:32
It seems that even after removing the files manually, the containers related to the zombie extensions are still started up when docker desktop is restarted.

**Comment by kc-dot-io** [comment] 2022-10-30 00:44
I also ran into this. I was able to follow the recommendations above to remove the local files to get the extension removed and then I was able to install, but for some reason now, no matter what I do to update the container, it always seems to load the image that was deployed when it was installed, but wasn't. Is there an image cache for the extension VM or something?

@averche did you find a solution?

**Comment by kc-dot-io** [comment] 2022-10-30 05:12
Ok found a solution for why it seemed my local was caching the zombie container after I removed the files and reinstalled everything. It seems it was actually being cached in electron so I purged the [electron cache](https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell). Spent quite a bit of time debugging this, would be great if there was a way to expose this via extensions settings.

**Comment by felipecruz91** [comment] 2022-12-09 11:14
In the latest version of Docker Desktop (4.15) I cannot replicate the issue anymore. If you install an extension whose image doesn't have a namespace (e.g. `foo` instead of `foo/bar`), the extension can be removed successfully:

```shell
$ docker extension install -f foo
...

$ docker extension ls
ID                  PROVIDER            VERSION             UI                  VM                  HOST
foo                 Felipe                                  1 tab(Foo)        Running(1)          -

$ docker extension rm foo
Removing extension foo...
Removing extension VM service...
Extension removed from Desktop VM
VM service socket forwarding stopped
Extension UI tab Foo removed
Extension image foo removed
```

**Comment by felipecruz91** [comment] 2022-12-09 11:19
Closing issue as this has been fixed. Feel free to re-open it if you come across this problem again.

**Closed by felipecruz91** 2022-12-09 11:19 UTC
Labels: bug
